# Generated by Django 5.2.13 on 2026-05-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='accounts.cidadao')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('rejeitada', 'Rejeitada')], default='aberta', max_length=20)),
                ('setor_responsavel', models.CharField(blank=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_prazo', models.DateTimeField(blank=True, null=True)),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='accounts.cidadao')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='servicos.servico')),
                ('servidor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='accounts.servidor')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
