# Generated by Django 5.2.13 on 2026-05-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('emissao', 'Emissão de Documento'), ('agendamento', 'Agendamento'), ('protocolo', 'Protocolo'), ('segunda_via', 'Segunda Via')], max_length=20)),
                ('prazo_dias', models.IntegerField(default=5)),
                ('setor_responsavel', models.CharField(default='Atendimento Geral', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('servico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicos.servico')),
                ('local_atendimento', models.CharField(max_length=200)),
                ('horarios_disponiveis', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
            bases=('servicos.servico',),
        ),
        migrations.CreateModel(
            name='EmissaoDocumento',
            fields=[
                ('servico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicos.servico')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('requer_autenticacao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Emissão de Documento',
                'verbose_name_plural': 'Emissões de Documento',
            },
            bases=('servicos.servico',),
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('servico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicos.servico')),
                ('orgao_destino', models.CharField(max_length=200)),
                ('permite_anonimo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
            },
            bases=('servicos.servico',),
        ),
        migrations.CreateModel(
            name='SegundaVia',
            fields=[
                ('servico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicos.servico')),
                ('documento_original', models.CharField(max_length=100)),
                ('taxa_emissao', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Segunda Via',
                'verbose_name_plural': 'Segundas Vias',
            },
            bases=('servicos.servico',),
        ),
    ]
