# Generated by Django 5.2.13 on 2026-05-25 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacao', 'Confirmação'), ('atualizacao', 'Atualização de Status'), ('lembrete', 'Lembrete')], default='confirmacao', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='solicitacoes.solicitacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoAtualizacao',
            fields=[
            ],
            options={
                'verbose_name': 'Notificação de Atualização',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notificacoes.notificacao',),
        ),
        migrations.CreateModel(
            name='NotificacaoConfirmacao',
            fields=[
            ],
            options={
                'verbose_name': 'Notificação de Confirmação',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notificacoes.notificacao',),
        ),
        migrations.CreateModel(
            name='NotificacaoLembrete',
            fields=[
            ],
            options={
                'verbose_name': 'Notificação de Lembrete',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notificacoes.notificacao',),
        ),
    ]
